# -*- coding: utf-8 -*-
"""svNIT_FDP_DAY1_sPAM_DETECTION_m1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PvIWF19Z4BjbJmzr_kfjUHMP84aym36p
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

df = pd.read_csv("data/spam.csv", encoding="latin-1")
df.head()

df = df[['v1','v2']]
df.columns = ['label','message']

df['label'] = df['label'].map({'ham':0,'spam':1})
df.head()

df.info()
df['label'].value_counts()

X = df['message']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

vectorizer = TfidfVectorizer(stop_words='english')

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

model = LogisticRegression()
model.fit(X_train_vec, y_train)

y_pred = model.predict(X_test_vec)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d')
plt.show()

msg = ["Congratulations! You won free cash. Click now!"]

msg_vec = vectorizer.transform(msg)
print("Spam" if model.predict(msg_vec)[0]==1 else "Not Spam")

import pickle
import os

# create models folder if not exists
os.makedirs("models", exist_ok=True)

# save model and vectorizer
pickle.dump(model, open("models/model.pkl", "wb"))
pickle.dump(vectorizer, open("models/vectorizer.pkl", "wb"))

print("Model and vectorizer saved inside /models folder")

